/**
 * Environment Variables Generator
 * 
 * This script generates the env-config.js file with environment variables
 * that need to be exposed to the browser
 */

const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Environment variables that should be exposed to the browser
// IMPORTANT: Never include sensitive API keys here
const browserEnvVars = [
  'NODE_ENV',
  'APP_PORT',
  'ENABLE_CACHING',
  'DEFAULT_GRID_LAYOUT',
  'MAX_CARDS_PER_VIEW',
  'ENABLE_ANIMATIONS',
  // API endpoints (but NOT API keys)
  'SERPAPI_ENDPOINT',
  'SEARCH1_ENDPOINT',
  'PERPLEXITY_ENDPOINT'
];

// Get the values of the environment variables
const envValues = browserEnvVars.reduce((acc, key) => {
  if (process.env[key] !== undefined) {
    acc[key] = process.env[key];
  }
  return acc;
}, {});

// Generate the env-config.js content
const envConfigContent = `
/**
 * Runtime environment configuration
 * Generated on ${new Date().toISOString()}
 * 
 * DO NOT EDIT THIS FILE DIRECTLY
 * It is generated by the generate-env.js script
 */
window.__ENV__ = ${JSON.stringify(envValues, null, 2)};
`;

// Write the file
const outputPath = path.join(__dirname, '../public/env-config.js');
fs.writeFileSync(outputPath, envConfigContent);

console.log(`Environment configuration generated at ${outputPath}`);
console.log(`Exposed variables: ${Object.keys(envValues).join(', ')}`);
